[tools]
node = "latest"
go = "latest"
operator-sdk = "latest"
ripgrep = "latest"
websocat = "latest"
maven = "3.9.4"
python = "latest"
youtube-dl = "latest"
jq = "latest"
kubectl = "latest"
krew = "latest"
neovim = "latest"
kustomize = "latest"
packer = "1.9.4"
cilium-cli = "latest"
cilium-hubble = "latest"
yq = "latest"
eza = "latest"
helm = "latest"
usage = "latest"
kubectx = "latest"
"cargo:zoxide" = "latest"
tmux = "latest"
opentofu = "latest"
bat = "latest"
java = "21"
stern = "latest"
argocd = "latest"
zig = "latest"
kubens = "latest"
ollama = "latest"
golangci-lint = "latest"
goreleaser = "latest"
yt-dlp = "latest"
rust = "latest"
"go:sigs.k8s.io/kind" = "latest"
"go:github.com/onsi/ginkgo/v2/ginkgo" = "latest"
"github:cli/cli" = "latest"
"go:github.com/gohugoio/hugo" = { version = "latest", tags = "extended" }
"go:github.com/nektos/act" = "latest"

[alias]
operator-sdk = "https://github.com/Medium/asdf-operator-sdk"
ripgrep = "https://gitlab.com/wt0f/asdf-ripgrep"
websocat = "https://github.com/bdellegrazie/asdf-websocat"
maven = "https://github.com/halcyon/asdf-maven"
youtube-dl = "https://github.com/iul1an/asdf-youtube-dl"
jq = "https://github.com/lsanwick/asdf-jq"
kubectl = "https://github.com/asdf-community/asdf-kubectl"
krew = "https://github.com/bjw-s/asdf-krew"
neovim = "https://github.com/richin13/asdf-neovim"
kustomize = "https://github.com/Banno/asdf-kustomize"
packer = "https://github.com/asdf-community/asdf-hashicorp"
cilium-cli = "https://github.com/carnei-ro/asdf-cilium-cli.git"
cilium-hubble = "https://github.com/NitriKx/asdf-cilium-hubble.git"
kubens = "https://gitlab.com/wt0f/asdf-kubectx"

[settings]
trusted_config_paths = [
  '$ENV{HOME}/./config/mise/config.toml',
]
experimental = true
